# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
domain_name: "meusetech"
email_provider_username: "mtechdev01@gmail.com"
email_provider_password: "MeuseTechDev01"

development:
  secret_key_base: 3c28fefc8600bf6541b7f9638e831d0728ec1429a2cf6784aeaf4dbc373544b3a1dc2974226d94543287f31eaad0ddf49e9333631d8a1044f5c39fd36e97859d

test:
  secret_key_base: 1376a2510f760a7a1b7dca51c0450d161abba1c3a7515483ecd899b876feaa4d1f56a7b9614577dee8851d954bb6b7915195b7b9ba039a371c8fe802ba596a46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
